//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmLibrary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilmLibrary()
        {
            this.FilmCountry = new HashSet<FilmCountry>();
            this.FilmGenre = new HashSet<FilmGenre>();
            this.UserFavorite = new HashSet<UserFavorite>();
            this.UserView = new HashSet<UserView>();
            this.FilmProductionStaff = new HashSet<FilmProductionStaff>();
            this.PromoTrailer = new HashSet<PromoTrailer>();
            this.SeriesSeason = new HashSet<SeriesSeason>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string FullDescription { get; set; }
        public string ShortDecription { get; set; }
        public Nullable<int> AgeRestriction { get; set; }
        public Nullable<System.DateTime> WorldPremiereDate { get; set; }
        public Nullable<System.DateTime> RussiaPremiereDate { get; set; }
        public Nullable<decimal> BudgetNum { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public Nullable<bool> IsSeries { get; set; }
        public string FilmLink { get; set; }
        public string PromoPosterLink { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmCountry> FilmCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmGenre> FilmGenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavorite> UserFavorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserView> UserView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmProductionStaff> FilmProductionStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoTrailer> PromoTrailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeriesSeason> SeriesSeason { get; set; }
    }
}
