//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineCinema_dataEntities : DbContext
    {
        public OnlineCinema_dataEntities()
            : base("name=OnlineCinema_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<FilmCountry> FilmCountry { get; set; }
        public virtual DbSet<FilmGenre> FilmGenre { get; set; }
        public virtual DbSet<FilmLibrary> FilmLibrary { get; set; }
        public virtual DbSet<FilmProductionStaff> FilmProductionStaff { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<ProductionStaff> ProductionStaff { get; set; }
        public virtual DbSet<PromoPoster> PromoPoster { get; set; }
        public virtual DbSet<PromoTrailer> PromoTrailer { get; set; }
        public virtual DbSet<SeriesEpisode> SeriesEpisode { get; set; }
        public virtual DbSet<SeriesSeason> SeriesSeason { get; set; }
        public virtual DbSet<StaffRole> StaffRole { get; set; }
        public virtual DbSet<StarReview> StarReview { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TextReview> TextReview { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
        public virtual DbSet<UserView> UserView { get; set; }
        public virtual DbSet<View_FilmGenreList> View_FilmGenreList { get; set; }
        public virtual DbSet<View_MainPageListNum1> View_MainPageListNum1 { get; set; }
    }
}
