//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesEpisode
    {
        public int Id { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public int EpisodeNumber { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PremiereDate { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public string EpisodeLink { get; set; }
    
        public virtual SeriesSeason SeriesSeason { get; set; }
    }
}
