//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarReview
    {
        public int Id { get; set; }
        public Nullable<int> UserViewId { get; set; }
        public decimal StarAmount { get; set; }
        public System.DateTime ReviewTime { get; set; }
    
        public virtual UserView UserView { get; set; }
    }
}
