//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserItemViems
    {
        public string UserName { get; set; }
        public string Title { get; set; }
        public string PromoPosterLink { get; set; }
        public Nullable<System.DateTime> ViewTime { get; set; }
        public int UserId { get; set; }
    }
}
