//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1234.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FilmProduction
    {
        public string FullName { get; set; }
        public string PhotoLink { get; set; }
        public string ActorRole { get; set; }
        public int FilmId { get; set; }
        public string Title { get; set; }
    }
}
